### ISSUE TITLE
A small bug

### ISSUE THREAD

**Issue by gyj155** [changhaonan/A3VLM#8]
Thank you for sharing your work.
After running the script `bash model/accessory/scripts/a3vlm_infer.sh`, I encountered the following error in the file `A3VLM/model/accessory/model/meta.py` at line 225, specifically in the function `get_trainable_params`:

```python
File "A3VLM/model/accessory/model/meta.py", line 225, in get_trainable_params
    llma_trainable = self.llma.get_trainable_params(pretrain_stage)
```

The error message was:

> `TypeError: Transformer.get_trainable_params() takes 1 positional argument but 2 were given`

To investigate, I looked into the file `LLaMA2-Accessory/accessory/model/LLM/llama_ens5.py`, where the model above is instantiated. I found this definition of `get_trainable_params`:

```python
def get_trainable_params(self):
    trainable = {}
    no_train_prefix = ["qformer.", "openclip_convnext_xxl.", "clip.", "dinov2_vitg14."]
    for name, para in self.named_parameters():
        if not any([name.startswith(_) for _ in no_train_prefix]):
            trainable[name] = para
    return trainable
```

This definition does not accept any parameters, meaning the function should indeed be called without arguments. I removed the extra parameter in the function call, and this resolved the issue.

**Comment by SiyuanHuang95** [comment]
1. thanks for your interest!
2. Yes but. This is a historical problem where we tried to use the two-stage training to gradually inject point cloud knowledge into the model at the early stage of this project, so that is where this para comes from
3. when using this project, one most easy way to walk around is just to comment it out!
4. If you have any other questions, just let me know!

**Comment by gyj155** [comment]
Thank you for your response!
